button:
-
  name: "企业详情"
  sub_button:
  -
    type: "view"
    name: "品牌主页"
    url: "http://closet.tallty.com/"
  -
    type: "view"
    name: "会员权益"
    url: "http://closet.tallty.com/vip"
  -
    type: "view"
    name: "收费详情"
    url: "http://closet.tallty.com/charge_detail"
  -
    type: "view"
    name: "服务流程"
    url: "http://closet.tallty.com/process"
  -
    type: "view"
    name: "常见问题"
    url: "http://closet.tallty.com/help"
-
  name: '在线预约'
  sub_button: 
  -
    type: "view"
    name: "预约存衣"
    url:  "http://closet.tallty.com/appointment"
  -
    type: "view"
    name: "预约取衣"
    url:  "http://closet.tallty.com/cart"
-
  name: "个人中心"
  sub_button: 
  -
    type: "view"
    name: "我的订单"
    url:  "http://closet.tallty.com/orders"
  -
    type: "view"
    name: "我的衣橱"
    url:  "http://closet.tallty.com/MyCloset"
  -
    type: "view"
    name: "我的账户"
    url:  "http://closet.tallty.com/user"
  -
    type: "view"
    name: "华服租赁"
    url:  "http://closet.tallty.com/rent"
  -
    type: "view"
    name: "一键转卖"
    url:  "http://closet.tallty.com/sell"

