button:
-
  name: '气象博物馆'
  sub_button:
  -
    type: 'view'
    name: '展馆概述'
    url: 'http://museum.tallty.com/presentation'
  -
    type: 'view'
    name: '展馆导览'
    url: 'http://museum.tallty.com/static/panorama/index14.html'
  -
    type: 'view'
    name: '展点介绍'
    url: 'http://museum.tallty.com/display'
-
  name: '线上活动'
  sub_button:
  -
    type: 'view'
    name: '摄影展投稿'
    url: 'https://jinshuju.net/f/Depewy'
  -
    type: 'view'
    name: '有奖竞答'
    url: 'https://jinshuju.net/f/abdOaT'
-
  name: '服务中心'
  sub_button:
  -
    type: 'view'
    name: '留言建议'
    url:  'http://museum.tallty.com/feedback'
  -
    type: 'view'
    name: '参观预约'
    url:  'http://museum.tallty.com/create_booking'
  # -
  #   type: 'view'
  #   name: '我的视频'
  #   url: 'http://museum.tallty.com/videos'
  -
    type: 'view'
    name: '一键导航'
    url: 'http://museum.tallty.com/open_location'
  -
    type: 'view'
    name: '个人中心'
    url: 'http://museum.tallty.com/personal'
